function [U] = advance_time(U,P,T,gamma,R,mu,k,T_amb,M_inf,deltaXi,deltaEta,delta_t,Xi_x,Xi_y,Eta_x,Eta_y,J)
arguments (Input)
    U (4,:,:) double
    P (:,:) double
    T (:,:) double
    gamma (1,1) double
    R (1,1) double
    mu (1,1) double
    k (1,1) double
    T_amb (1,1) double
    M_inf (1,1) double
    deltaXi (1,1) double
    deltaEta (1,1) double
    delta_t (1,1) double
    Xi_x (:,:) double
    Xi_y (:,:) double
    Eta_x (:,:) double
    Eta_y (:,:) double
    J (:,:) double

end
arguments (Output)
    U (4,:,:) double
end
    coder.gpu.kernelfun;
    [~, IL, JL] = size(U);
    RHO = 1;
    M = 2;
    N = 3;
    E = 4;
    
    c_amb = sqrt(gamma*R*T_amb);
    dPdU = @(Ui) [
    (gamma-1)*(Ui(M)^2+Ui(N)^2)/(2*Ui(RHO)^2)
    -Ui(M)*(gamma-1)/Ui(RHO)
    -Ui(N)*(gamma-1)/Ui(RHO)
    gamma-1
    ];
    dTdU = @(Ui) [
        (gamma-1)*(Ui(M)^2+Ui(N)^2-Ui(E)*Ui(RHO))/(R*Ui(RHO)^3)
        -Ui(M)*(gamma-1)/(R*Ui(RHO)^2)
        -Ui(N)*(gamma-1)/(R*Ui(RHO)^2)
        (gamma-1)/(R*Ui(RHO))
        ];
    dudU = @(Ui) [-Ui(M)/Ui(RHO)^2; 1/Ui(RHO); 0; 0];
    dvdU = @(Ui) [-Ui(N)/Ui(RHO)^2; 0; 1/Ui(RHO); 0];

    A = zeros(4,4,IL,JL);
    B = zeros(4,4,IL,JL);
    specrad_A = zeros(IL,JL);
    specrad_B = zeros(IL,JL);
    Av = zeros(4,4,IL,JL);
    Bv = zeros(4,4,IL,JL);
    Av_xi = zeros(4,4,IL,JL);
    Bv_xi = zeros(4,4,IL,JL);
    Av_eta = zeros(4,4,IL,JL);
    Bv_eta = zeros(4,4,IL,JL);
    RHS = zeros(4,IL,JL);
    DeltaJU = zeros(4,IL,JL);


    % Calculate Gradients for Jacobians + Shear Stresses
    [T_xi, T_eta] = grad2d(@(i,j) T(i,j), IL, JL, deltaXi, deltaEta);
    [U_xi, U_eta] = grad2d(@(i,j) U(:,i,j), IL, JL, deltaXi, deltaEta, 4);
    
    [u_xi, u_eta] = grad2d(@(i,j) U(M,i,j)/U(RHO,i,j), IL, JL, deltaXi, deltaEta);
    [v_xi, v_eta] = grad2d(@(i,j) U(N,i,j)/U(RHO,i,j), IL, JL, deltaXi, deltaEta);
    u_x = Xi_x .* u_xi + Eta_x .* u_eta;
    u_y = Xi_y .* u_xi + Eta_y .* u_eta;
    v_x = Xi_x .* v_xi + Eta_x .* v_eta;
    v_y = Xi_y .* v_xi + Eta_y .* v_eta;
    Jtau_xx = J.*mu.*(4*u_x - 2*v_y)/3;
    Jtau_yy = J.*mu.*(4*v_y - 2*u_x)/3;
    Jtau_xy = J.*mu.*(u_y+v_x);

    T_x = @(i,j) T_xi(i,j)*Xi_x(i,j) + T_eta(i,j)*Eta_x(i,j);
    T_y = @(i,j) T_xi(i,j)*Xi_y(i,j) + T_eta(i,j)*Eta_y(i,j);

   
    % Calculate the A/B Matrices
    for i=1:IL
        for j=1:JL
            A(:,:,i,j) = calcA(P(i,j), U(E,i,j), gamma, U(M,i,j), U(N,i,j), U(RHO,i,j));
            B(:,:,i,j) = calcB(P(i,j), U(E,i,j), gamma, U(M,i,j), U(N,i,j), U(RHO,i,j));
            specrad_A(i,j) = abs(U(M,i,j)/U(RHO,i,j)) + ...
                sqrt(gamma*P(i,j)/U(RHO,i,j));
            specrad_B(i,j) = abs(U(N,i,j)/U(RHO,i,j)) + ...
                sqrt(gamma*P(i,j)/U(RHO,i,j));
            Av(:,:,i,j) = dFv_dU(R, U(E,i,j), U_eta(E,i,j), U_xi(E,i,j), ...
                Eta_x(i,j), Eta_y(i,j), gamma, k, U(M,i,j), ...
                U_eta(M,i,j), U_xi(M,i,j), mu, U(N,i,j), U_eta(N,i,j), ...
                U_xi(N,i,j), U(RHO,i,j), U_eta(RHO,i,j), U_xi(RHO,i,j), ...
                Xi_x(i,j), Xi_y(i,j));
            Bv(:,:,i,j) = dGv_dU(R, U(E,i,j), U_eta(E,i,j), U_xi(E,i,j), ...
                Eta_x(i,j), Eta_y(i,j), gamma, k, U(M,i,j), ...
                U_eta(M,i,j), U_xi(M,i,j), mu, U(N,i,j), U_eta(N,i,j), ...
                U_xi(N,i,j), U(RHO,i,j), U_eta(RHO,i,j), U_xi(RHO,i,j), ...
                Xi_x(i,j), Xi_y(i,j));
            Av_xi(:,:,i,j) = dFv_dU_xi(R, U(E,i,j), gamma, k, U(M,i,j), ...
                mu, U(N,i,j), U(RHO,i,j), Xi_x(i,j), Xi_y(i,j));
            Bv_xi(:,:,i,j) = dGv_dU_xi(R, U(E,i,j), gamma, k, U(M,i,j), ...
                mu, U(N,i,j), U(RHO,i,j), Xi_x(i,j), Xi_y(i,j));
            Av_eta(:,:,i,j) = dFv_dU_eta(R, U(E,i,j), Eta_x(i,j), Eta_y(i,j), ...
                gamma, k, U(M,i,j), mu, U(N,i,j), U(RHO,i,j));
            Bv_eta(:,:,i,j) = dGv_dU_eta(R, U(E,i,j), Eta_x(i,j), Eta_y(i,j), ...
                gamma, k, U(M,i,j), mu, U(N,i,j), U(RHO,i,j));
        end
    end
    % Explicit portion
    energy_term_f = @(i,j) ...
        (U(M,i,j)*Jtau_xx(i,j) + U(N,i,j)*Jtau_xy(i,j))/U(RHO,i,j) + ...
        J(i,j)*k*T_x(i,j);
    energy_term_g = @(i,j) ...
        (U(M,i,j)*Jtau_xy(i,j) + U(N,i,j)*Jtau_yy(i,j))/U(RHO,i,j) + ...
        J(i,j)*k*T_y(i,j);
    [Fhat_v_explicit, ~] = grad2d(@(i,j) ...
        Xi_x(i,j)*[0; Jtau_xx(i,j); Jtau_xy(i,j); energy_term_f(i,j)] + ...
        Xi_y(i,j)*[0; Jtau_xy(i,j); Jtau_yy(i,j); energy_term_g(i,j)], ...
        IL, JL, deltaXi, deltaEta, 4);
    [~, Ghat_v_explicit] = grad2d(@(i,j) ...
        Eta_x(i,j)*[0; Jtau_xx(i,j); Jtau_xy(i,j); energy_term_f(i,j)] + ...
        Eta_y(i,j)*[0; Jtau_xy(i,j); Jtau_yy(i,j); energy_term_g(i,j)], ...
        IL, JL, deltaXi, deltaEta, 4);
    for i=2:IL-1
        for j=2:JL-1
            RHS(:,i,j) = [0;0;0;0];
            % Xi direction
            Aplus_upwind = (A(:,:,i-1,j) + eye(4)*specrad_A(i-1,j))/2;
            Aplus = (A(:,:,i,j) + eye(4)*specrad_A(i,j))/2;
            Aminus = (A(:,:,i,j) - eye(4)*specrad_A(i,j))/2;
            Aminus_downwind = (A(:,:,i+1,j) - eye(4)*specrad_A(i+1,j))/2;

            Bplus_upwind = (B(:,:,i-1,j) + eye(4)*specrad_B(i-1,j))/2;
            Bplus = (B(:,:,i,j) + eye(4)*specrad_B(i,j))/2;
            Bminus = (B(:,:,i,j) - eye(4)*specrad_B(i,j))/2;
            Bminus_downwind = (B(:,:,i+1,j) - eye(4)*specrad_B(i+1,j))/2;

            RHS(:,i,j) = RHS(:,i,j) - Fhat_v_explicit(:,i,j) + (...
                (Xi_x(i,j)*J(i,j)*Aplus*U(:,i,j) ...
                    - Xi_x(i-1,j)*J(i-1,j)*Aplus_upwind*U(:,i-1,j)) ...
                + (Xi_x(i+1,j)*J(i+1,j)*Aminus_downwind*U(:,i+1,j) ...
                    - Xi_x(i,j)*J(i,j)*Aminus*U(:,i,j)) ...
                + (Xi_y(i,j)*J(i,j)*Bplus*U(:,i,j) ...
                    - Xi_y(i-1,j)*J(i-1,j)*Bplus_upwind*U(:,i-1,j)) ...
                + (Xi_y(i+1,j)*J(i+1,j)*Bminus_downwind*U(:,i+1,j) ...
                    - Xi_y(i,j)*J(i,j)*Bminus*U(:,i,j))...
            )/deltaXi;
            % Eta direction
            Aplus_upwind = (A(:,:,i,j-1) + eye(4)*specrad_A(i,j-1))/2;
            Aminus_downwind = (A(:,:,i,j+1) - eye(4)*specrad_A(i,j+1))/2;
            Bplus_upwind = (B(:,:,i,j-1) + eye(4)*specrad_B(i,j-1))/2;
            Bminus_downwind = (B(:,:,i,j+1) - eye(4)*specrad_B(i,j+1))/2;

            RHS(:,i,j) = RHS(:,i,j) - Ghat_v_explicit(:,i,j) + ( ...
                (Eta_x(i,j)*J(i,j)*Aplus*U(:,i,j) ...
                    - Eta_x(i,j-1)*J(i,j-1)*Aplus_upwind*U(:,i,j-1)) ...
                + (Eta_x(i,j+1)*J(i,j+1)*Aminus_downwind*U(:,i,j+1) ...
                    - Eta_x(i,j)*J(i,j)*Aminus*U(:,i,j)) ...
                + (Eta_y(i,j)*J(i,j)*Bplus*U(:,i,j) ...
                    - Eta_y(i,j-1)*J(i,j-1)*Bplus_upwind*U(:,i,j-1)) ...
                + (Eta_y(i,j+1)*J(i,j+1)*Bminus_downwind*U(:,i,j+1) ...
                    - Eta_y(i,j)*J(i,j)*Bminus*U(:,i,j)) ...
            )/deltaEta;
            % Cross derivatives
            [DeltaJU_xi, DeltaJU_eta] = grad2d(@(i,j) DeltaJU(:,i,j)/J(i,j), ...
                IL, JL, deltaXi, deltaEta, 4);
            RHS(:,i,j) = RHS(:,i,j) - ( ...
                Xi_x(i+1,j)*J(i+1,j)*Av_eta(:,:,i+1,j)*DeltaJU_eta(:,i+1,j) ...
                - Xi_x(i-1,j)*J(i-1,j)*Av_eta(:,:,i-1,j)*DeltaJU_eta(:,i-1,j) ...
                + Xi_y(i+1,j)*J(i+1,j)*Bv_eta(:,:,i+1,j)*DeltaJU_eta(:,i+1,j) ...
                - Xi_y(i-1,j)*J(i-1,j)*Bv_eta(:,:,i-1,j)*DeltaJU_eta(:,i-1,j) ...
            )/(4*deltaXi);
            RHS(:,i,j) = RHS(:,i,j) - ( ...
                Eta_x(i,j+1)*J(i,j+1)*Av_xi(:,:,i,j+1)*DeltaJU_xi(:,i,j+1) ...
                - Eta_x(i,j-1)*J(i,j-1)*Av_xi(:,:,i,j-1)*DeltaJU_xi(:,i,j-1) ...
                + Eta_y(i,j+1)*J(i,j+1)*Bv_xi(:,:,i,j+1)*DeltaJU_xi(:,i,j+1) ...
                - Eta_y(i,j-1)*J(i,j-1)*Bv_xi(:,:,i,j-1)*DeltaJU_xi(:,i,j-1) ...
            )/(4*deltaEta);
            % Finally... multiply by -delta t (negative to move to RHS)
            RHS(:,i,j) = RHS(:,i,j) * -delta_t;
        end
    end
    UP = zeros(4,4,JL-1);
    MD = zeros(4,4,JL);
    DN = zeros(4,4,JL-1);
    YY = zeros(4,JL);
    % Solve across the eta direction
    for i=2:IL-1
        for j=2:JL-1
            YY(:,j) = RHS(:,i,j)*(2/delta_t);
            UP(:,:,j-1) = ( ...
                Eta_x(i,j-1)*(A(:,:,i,j-1) + eye(4)*specrad_A(i,j-1)) ...
                + Eta_y(i,j-1)*(B(:,:,i,j-1) + eye(4)*specrad_B(i,j-1)) ...
            )/(-2*deltaEta);
            MD(:,:,j) = ( ...
                Eta_x(i,j)*(A(:,:,i,j) + eye(4)*specrad_A(i,j)) ...
                + Eta_y(i,j)*(B(:,:,i,j) + eye(4)*specrad_B(i,j)) ...
                - Eta_x(i,j)*(A(:,:,i,j) - eye(4)*specrad_A(i,j)) ...
                - Eta_y(i,j)*(B(:,:,i,j) - eye(4)*specrad_B(i,j)) ...
            )/(2*deltaEta);
            DN(:,:,j) = ( ...
                Eta_x(i,j+1)*(A(:,:,i,j+1) - eye(4)*specrad_A(i,j+1))...
                + Eta_y(i,j+1)*(B(:,:,i,j+1) - eye(4)*specrad_B(i,j+1)) ...
            )/(2*deltaEta);
            UP(:,:,j-1) = UP(:,:,j-1) - ( ...
                Eta_x(i,j-1)*Av_eta(:,:,i,j) + ...
                Eta_y(i,j-1)*Bv_eta(:,:,i,j) ...
            )/(deltaEta^2);
            MD(:,:,j) = MD(:,:,j) + 2*(...
                Eta_x(i,j)*Av_eta(:,:,i,j) + ...
                Eta_y(i,j)*Bv_eta(:,:,i,j) ...
            )/(deltaEta^2);
            DN(:,:,j) = DN(:,:,j) - ( ...
                Eta_x(i,j+1)*Av_eta(:,:,i,j) + ...
                Eta_y(i,j+1)*Bv_eta(:,:,i,j) ...
            )/(deltaEta^2);
            dAv = (Av_eta(:,:,i,j+1) - Av_eta(:,:,i,j-1))/(2*deltaEta);
            dBv = (Bv_eta(:,:,i,j+1) - Bv_eta(:,:,i,j-1))/(2*deltaEta);
            UP(:,:,j-1) = UP(:,:,j-1) + (...
                dAv*Eta_x(i,j-1) + dBv*Eta_y(i,j-1) ...
                + Av(:,:,i,j-1)*Eta_x(i,j-1) ...
                + Bv(:,:,i,j-1)*Eta_y(i,j-1) ...
            )/(2*deltaEta);
            DN(:,:,j) = DN(:,:,j) - ( ...
                dAv*Eta_x(i,j+1) + dBv*Eta_y(i,j+1) ...
                + Av(:,:,i,j+1)*Eta_x(i,j+1) ...
                + Bv(:,:,i,j+1)*Eta_y(i,j+1) ...
            )/(2*deltaEta);
            MD(:,:,j) = MD(:,:,j) + eye(4)*2/delta_t;
        end
        % Wall Boundary Conditions
        MD(:,:,1) = [
            0 1 0 0
            0 0 1 0
            dPdU(U(:,i,1)).'
            R*T_amb 0 0 (1-gamma)
        ] ./ J(i,1);
        DN(:,:,1) = [
            0 0 0 0
            0 0 0 0
            -dPdU(U(:,i,2)).'
            0 0 0 0
        ] ./ J(i,2);
        YY(:,1) = [0; 0; 0; 0];
        MD(:,:,end) = [
            0 1 0 0
            0 0 1 0
            dPdU(U(:,i,end)).'
            R*T_amb 0 0 (1-gamma)
        ] ./ J(i,end);
        UP(:,:,end-1) = [
            0 0 0 0
            0 0 0 0
            -dPdU(U(:,i,end-1)).'
            0 0 0 0
        ] ./ J(i,end-1);
        YY(:,end) = [0; 0; 0; 0];
        YY = block_tridiag(UP, MD, DN, YY);
        for j=1:JL
            DeltaJU(:,i,j) = YY(:,j);
        end
    end
    % Now in the Xi direction (DeltaJU is DeltaJU* right now)
    UP = zeros(4,4,IL-1);
    MD = zeros(4,4,IL);
    DN = zeros(4,4,IL-1);
    YY = zeros(4,IL);
    for j=2:JL-1
        for i=2:IL-1
            YY(:,i) = DeltaJU(:,i,j)*(2/delta_t);
            UP(:,:,i-1) = ( ...
                Xi_x(i-1,j)*(A(:,:,i-1,j) + eye(4)*specrad_A(i-1,j)) ...
                + Xi_y(i-1,j)*(B(:,:,i-1,j) + eye(4)*specrad_B(i-1,j)) ...
            )/(-2*deltaXi);
            MD(:,:,i) = ( ...
                Xi_x(i,j)*(A(:,:,i,j) + eye(4)*specrad_A(i,j)) ...
                + Xi_y(i,j)*(B(:,:,i,j) + eye(4)*specrad_B(i,j)) ...
                - Xi_x(i,j)*(A(:,:,i,j) - eye(4)*specrad_A(i,j)) ...
                - Xi_y(i,j)*(B(:,:,i,j) - eye(4)*specrad_B(i,j)) ...
            )/(2*deltaXi);
            DN(:,:,i) = ( ...
                Xi_x(i+1,j)*(A(:,:,i+1,j) - eye(4)*specrad_A(i+1,j))...
                + Xi_y(i+1,j)*(B(:,:,i+1,j) - eye(4)*specrad_B(i+1,j)) ...
            )/(2*deltaXi);
            UP(:,:,i-1) = UP(:,:,i-1) - ( ...
                Xi_x(i-1,j)*Av_xi(:,:,i,j) + ...
                Xi_y(i-1,j)*Bv_xi(:,:,i,j) ...
            )/(deltaXi^2);
            MD(:,:,i) = MD(:,:,i) + 2*(...
                Xi_x(i,j)*Av_xi(:,:,i,j) + ...
                Xi_y(i,j)*Bv_xi(:,:,i,j) ...
            )/(deltaXi^2);
            DN(:,:,i) = DN(:,:,i) - ( ...
                Xi_x(i+1,j)*Av_xi(:,:,i,j) + ...
                Xi_y(i+1,j)*Bv_xi(:,:,i,j) ...
            )/(deltaXi^2);
            dAv = (Av_xi(:,:,i+1,j) - Av_xi(:,:,i-1,j))/(2*deltaXi);
            dBv = (Bv_xi(:,:,i+1,j) - Bv_xi(:,:,i-1,j))/(2*deltaXi);
            UP(:,:,i-1) = UP(:,:,i-1) + (...
                dAv*Xi_x(i-1,j) + dBv*Xi_y(i-1,j) ...
                + Av(:,:,i-1,j)*Xi_x(i-1,j) ...
                + Bv(:,:,i-1,j)*Xi_y(i-1,j) ...
            )/(2*deltaXi);
            DN(:,:,i) = DN(:,:,i) - ( ...
                dAv*Xi_x(i+1,j) + dBv*Xi_y(i+1,j) ...
                + Av(:,:,i+1,j)*Xi_x(i+1,j) ...
                + Bv(:,:,i+1,j)*Xi_y(i+1,j) ...
            )/(2*deltaXi);
            MD(:,:,i) = MD(:,:,i) + eye(4)*2/delta_t;
        end
        % Inflow Boundary Conditions
        MD(:,:,1) = [
            -M_inf*c_amb 1 0 0
            0 0 1 0
            dPdU(U(:,1,j)).'
            dTdU(U(:,1,j)).'
        ] ./ J(1,j);
        DN(:,:,1) = [
            0 0 0 0
            0 0 0 0
            -dPdU(U(:,2,j)).'*2
            0 0 0 0
        ] ./ J(2,j);
        P3 = [
            0 0 0 0
            0 0 0 0
            dPdU(U(:,3,j)).'
            0 0 0 0
        ] ./ J(3,j);
        YY(:,1) = [0; 0; 0; 0];
        % Outflow Boundary Conditions
        MD(:,:,end) = [
            dTdU(U(:,end,j)).'
            dudU(U(:,end,j)).'
            dvdU(U(:,end,j)).'
            dPdU(U(:,end,j)).'
        ] ./ J(end,j);
        UP(:,:,end-1) = [
            -2*dTdU(U(:,end-1,j)).'
            -2*dudU(U(:,end-1,j)).'
            -2*dvdU(U(:,end-1,j)).'
            0 0 0 0
        ] ./ J(end-1,j);
        Q3 = [
            dTdU(U(:,end-2,j)).'
            dudU(U(:,end-2,j)).'
            dvdU(U(:,end-2,j)).'
            0 0 0 0
        ] ./ J(end-2,j);
        YY(:,end) = [0; 0; 0; 0];
        YY = block_tridiag(UP, MD, DN, YY, P3, Q3);
        for i=1:IL
            DeltaJU(:,i,j) = YY(:,i);
        end
    end
    % Update with calculated delta
    for i=2:IL-1
        for j=2:JL-1
            U(:,i,j) = U(:,i,j) + DeltaJU(:,i,j) / J(i,j);
        end
    end
end